name: Stateless Sync Tests

on:
  push:
    branches:
      - 'stateless_sync'
  pull_request:
    branches:
      - 'stateless_sync'
    types: [opened, synchronize, reopened]

concurrency:
  group: stateless-sync-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ENCLAVE_NAME: kurtosis-e2e

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest-8-cores
    timeout-minutes: 60

    steps:
      - name: Checkout Bor
        uses: actions/checkout@v4
        with:
          path: bor

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install build-essential

      - name: Pre kurtosis run
        uses: ./bor/.github/actions/kurtosis-pre-run

      - name: Build Bor Docker Image
        run: |
          cd bor
          docker build -t bor:local --file Dockerfile .

      - name: Checkout Heimdall-v2
        uses: actions/checkout@v4
        with:
          repository: 0xPolygon/heimdall-v2
          ref: stateless_sync
          path: heimdall-v2

      - name: Build Heimdall-v2 Docker Image
        run: |
          cd heimdall-v2
          docker build -t heimdall-v2:local --file Dockerfile .

      - name: Checkout Kurtosis
        uses: actions/checkout@v4
        with:
          repository: 0xPolygon/kurtosis-polygon-pos
          ref: stateless
          path: kurtosis-polygon-pos

      - name: Copy kurtosis config
        run: cp ./bor/.github/configs/kurtosis-e2e.yml ./kurtosis-polygon-pos/kurtosis-e2e.yml

      - name: Kurtosis run
        run: |
          cd kurtosis-polygon-pos
          kurtosis run --args-file kurtosis-e2e.yml --enclave ${{ env.ENCLAVE_NAME }} .

      - name: Inspect enclave
        run: |
          cd kurtosis-polygon-pos
          kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}

      - name: Run stateless sync tests
        run: |
          cd bor
          bash integration-tests/stateless_sync_test.sh

      - name: Test state syncs (post VeBlop HF)
        run: kurtosis service exec ${{ env.ENCLAVE_NAME }} test-runner "bats --filter-tags pos,bridge,matic,pol --recursive tests/"

      - name: Post kurtosis run
        if: always()
        uses: ./bor/.github/actions/kurtosis-post-run
        with:
          enclave_name: ${{ env.ENCLAVE_NAME }}
